### ISSUE TITLE
PRIMARY_CONSOLE and other macros essentially not working/useless

### ISSUE THREAD

**Issue by BarclayII** [davidgao/AIMv6#10]
More examples are:
`PAGE_ALLOCATOR`
`SIMPLE_ALLOCATOR`
etc.  Though only `PRIMARY_CONSOLE` matters, or should have mattered.

Consider removing the `#if PRIMARY_CONSOLE == uart_zynq`.

**Comment by davidgao** [comment]
I'll fix them today

Gan Quan <notifications@github.com>于2016年5月19日周四 下午11:21写道：

**Comment by davidgao** [comment]
Checked source code, these macros are provided in my AIM_ARG_WITH autoconf macro.
These defines are shown to the preprocessor so C code CAN check their values.
This allows the framework to change its behavior for hard-to-compat lower level implementations or just  to read them, in tests for example.
uart_zynq can compile as secondary driver, so this flag is necessary.

Generally this is a feature and not a bug.

**Comment by BarclayII** [comment]
I know your intention, but things like `#if PRIMARY_CONSOLE == uart_zynq` won't work as intended because the macro `uart_zynq` is undefined (and therefore empty).  Hence you could replace `uart_zynq` with any string and the code inside `#if` still gets compiled.

Even `#if PRIMARY_CONSOLE == gib_monies_plox` can gets your driver compiled.

**Comment by davidgao** [comment]
I'll make those macros expand to strings, so that I can have #if PRIMARY ==
"some_driver"

**Comment by BarclayII** [comment]
As far as I know C preprocessors don't support direct string comparison, so `#if PRIMARY == "gib_monies_plox"` won't work as well.

**Comment by davidgao** [comment]
solved with value comparision
