### ISSUE TITLE
Cross-platform libc dependency

### ISSUE THREAD

**Issue by BarclayII** [davidgao/AIMv6#2]
When I was trying to run `configure` with host mips64-linux-gnu I got `configure` complaining that my `mips64-linux-gnu-gcc` compiler lacks a MIPS64 libc and refused to go any further.

I don't think a cross-platform libc is *absolutely* necessary so I'm wondering how to skip this check.

**Comment by davidgao** [comment]
that check is for the compiler, so it cannot be skipped. Consider building newlib in your toolchain
