### ISSUE TITLE
renaming `early_kva2pa()` and `early_pa2kva()` and clarifying `RAM_PHYSBASE`

### ISSUE THREAD

**Issue by BarclayII** [davidgao/AIMv6#9]
1. Both functions stand for converting between kernel virtual address and physical address.  However, in MIPS systems the mapping between `kva` and `pa` are *fixed*, and there are *two* mappings for cached and uncached accesses.  We should probably rename them to `premap_addr`/`postmap_addr` or `lo2hi`/`hi2lo` or something as the original names are too ambiguous.
2. I think `RAM_PHYSBASE` should stand for "the base address of RAM", and in this case, we probably would not want the kernel to load at `RAM_PHYSBASE`, but rather some macro representing "kernel load address" `KERNLOAD`, which, could be RAM base address, or something else.

**Comment by davidgao** [comment]
both point agreed. please commit change.
